export function createObjects(centerX, centerY) {
    return [
        {
            el: document.getElementById("background"),
            x: centerX,
            y: centerY,
            targetX: centerX,
            targetY: centerY,
            maxRadius: 20,
            speed: 0.04,
            offsetX: 0,
            offsetY: 0,
            behavior: "flee", // 👈 これが逃げる
        }, {
            el: document.getElementById("back-hear"),
            x: centerX,
            y: centerY,
            targetX: centerX,
            targetY: centerY,
            maxRadius: 4,
            speed: 0.02,
            offsetX: 0,
            offsetY: 0,
            behavior: "flee",
        },
        {
            el: document.getElementById("face"),
            x: centerX,
            y: centerY,
            targetX: centerX,
            targetY: centerY,
            maxRadius: 11,
            speed: 0.03,
            offsetX: 0,
            offsetY: 0,
            behavior: "chase",
        },
        {
            el: document.getElementById("front-hear-2"),
            x: centerX,
            y: centerY,
            targetX: centerX,
            targetY: centerY,
            maxRadius: 12,
            speed: 0.04,
            offsetX: 0,
            offsetY: 0,
            behavior: "chase",
        },
        {
            el: document.getElementById("front-hear-1"),
            x: centerX,
            y: centerY,
            targetX: centerX,
            targetY: centerY,
            maxRadius: 13,
            speed: 0.04,
            offsetX: 0,
            offsetY: 0,
            behavior: "chase",
        },
        {
            el: document.getElementById("mouth"),
            x: centerX,
            y: centerY,
            targetX: centerX,
            targetY: centerY,
            maxRadius: 17,
            speed: 0.22,
            offsetX: 0,
            offsetY: 0,
            behavior: "chase",
        },
        {
            el: document.getElementById("eye-back"),
            x: centerX,
            y: centerY,
            targetX: centerX,
            targetY: centerY,
            maxRadius: 18,
            speed: 0.08,
            offsetX: 0,
            offsetY: 0,
            behavior: "chase",
        },
        {
            el: document.getElementById("eye"),
            x: centerX,
            y: centerY,
            targetX: centerX,
            targetY: centerY,
            maxRadius: 18,
            speed: 0.08,
            offsetX: 0,
            offsetY: 0,
            behavior: "chase",
        },
        {
            el: document.getElementById("under-eye"),
            x: centerX,
            y: centerY,
            targetX: centerX,
            targetY: centerY,
            maxRadius: 18,
            speed: 0.04,
            offsetX: 0,
            offsetY: 0,
            behavior: "chase",
        },
        {
            el: document.getElementById("eyelid-2"),
            x: centerX,
            y: centerY,
            targetX: centerX,
            targetY: centerY,
            maxRadius: 20,
            speed: 0.04,
            offsetX: 0,
            offsetY: 0,
            behavior: "chase",
        },
        {
            el: document.getElementById("eyelid"),
            x: centerX,
            y: centerY,
            targetX: centerX,
            targetY: centerY,
            maxRadius: 20,
            speed: 0.04,
            offsetX: 0,
            offsetY: 0,
            behavior: "chase",
        },
        {
            el: document.getElementById("eyebrow"),
            x: centerX,
            y: centerY,
            targetX: centerX,
            targetY: centerY,
            maxRadius: 13,
            speed: 0.04,
            offsetX: 0,
            offsetY: 0,
            behavior: "chase",
        },
        {
            el: document.getElementById("hot_spot"),
            x: centerX,
            y: centerY,
            targetX: centerX,
            targetY: centerY,
            maxRadius: 20,
            speed: 0.04,
            offsetX: 0,
            offsetY: -100,
        },
    ];
}